apiVersion: v1
kind: Pod
metadata:
  name: efs-bootstrap
spec:
  containers:
  - name: efs-bootstrap
    image: busybox:latest
    command: ["chmod"]
    args: ["777", "/data/"]
    volumeMounts:
    - name: persistent-storage
      mountPath: /data
  volumes:
  - name: persistent-storage
    persistentVolumeClaim:
      claimName: efs-claim
