apiVersion: v1
kind: Pod
metadata:
  name: rr
spec:
  containers:
  - name: efs-bootstrap
    image: busybox:latest
    command: ["rm"]
    args: ["-r", "/data/results/19082021/"]
    volumeMounts:
    - name: persistent-storage
      mountPath: /data
  volumes:
  - name: persistent-storage
    persistentVolumeClaim:
      claimName: efs-claim

